### ISSUE TITLE
How to subscribe to stream ?

### ISSUE THREAD

**Issue by checkraiser** [arkency/http_eventstore#11]
In the blog post for this gem, i read that there is a method `subscribe` to enable subscriptions from EventStore.
But there is no method like that till now.
Do you know how to implement ?

**Comment by andrzejkrzywda** [comment]
The blogpost you mentioned on twitter is about another gem - RailsEventStore.

Our long-term goal is to make those 2 gems share the same public API, but we're not there yet.

**Comment by checkraiser** [comment]
Thank you for clarifying +1
