### ISSUE TITLE
append_event_to_stream needs content type 'application/vnd.eventstore.events+json'

### ISSUE THREAD

**Issue by hallgren** [arkency/http_eventstore#13]
http://docs.geteventstore.com/http-api/3.5.0/writing-to-a-stream/

To be able to append more than one event in one request the content type 'application/vnd.eventstore.events+json' is needed.

As I understand it version 2.* of `Event Store` does not support this content type and `http_eventstore` only use the content type `application/json` making the append_event_to_stream function broken.

Is the content type 'application/vnd.eventstore.events+json' something 'http_eventstore' intend to support?

I love to help but think a discussion is needed in how the support of 2.* and 3.* of `Event Store` should work.

BR Morgan

**Comment by mpraglowski** [comment]
> To be able to append more than one event in one request the content type 'application/vnd.eventstore.events+json' is needed.

Yes, I've planed to work on that soon but any help will be appreciated :) PR please ;)

> Is the content type 'application/vnd.eventstore.events+json' something 'http_eventstore' intend to support?

Sure.

> I love to help but think a discussion is needed in how the support of 2.* and 3.* of Event Store should work.

There is a lot of new things in `Event Store` between versions 2.x and 3.x. I would like to avoid supporting 2 versions here. The simplest solution would be make a branch `EventStore 2.x` with current code and next release or `http_eventstore` could support only 3.x version.

**Comment by hallgren** [comment]
Thanks for the reply. I try to work on it.

I plan to use the `http_eventstore` as part of a driver to https://github.com/Sandthorn/sandthorn. :)

**Comment by hallgren** [comment]
I started a branch https://github.com/hallgren/http_eventstore/tree/event_store_version_3. I'm not sure how to best collaborate github wish. It seems to early to create a PR of this branch.

**Comment by mpraglowski** [comment]
PR might be created on early stage of work - it is easier to discuss things when you see the code - feel free to create a PR - it does not have to be merged immediately.

**Comment by hallgren** [comment]
Great.
